before:
  hooks:
    - go mod tidy
builds:
  - id: dns-server
    binary: dns-server
    main: ./cmd/dns-server
    flags:
      - -tags=embed
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
release:
  prerelease: auto
