/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get blocklist
         * @description Returns all domains in the blocklist
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.BlockedDomain"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add to blocklist
         * @description Blocks a new domain
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Domain and Wildcard flag */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.AddBlockRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        /**
         * Remove from blocklist
         * @description Unblocks a domain
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Domain name */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.RemoveBlockRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get query logs
         * @description Returns the most recent DNS query logs
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.QueryLog"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Clear query logs
         * @description Deletes all DNS query logs from the database
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get custom DNS records
         * @description Returns all manually configured DNS records
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Add custom DNS record
         * @description Creates a new custom DNS entry
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Domain and IP */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.AddRecordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        /**
         * Delete custom DNS record
         * @description Removes a custom DNS entry
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Domain name */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.DeleteRecordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: boolean;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server status and stats
         * @description Returns query statistics, cache info, and uptime
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Stats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the service status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        "models.Action": "forwarded" | "blocked" | "custom" | "cached" | "error";
        "models.AddBlockRequest": {
            /** @example ads.example.com */
            domain: string;
            /** @example false */
            wildcard?: boolean;
        };
        "models.AddRecordRequest": {
            /** @example mydevice.local */
            domain: string;
            /** @example 192.168.1.100 */
            ip: string;
        };
        "models.BlockedDomain": {
            /** @example 2024-10-25T10:00:00Z */
            added_at?: string;
            /** @example ads.example.com */
            domain?: string;
            /** @example false */
            wildcard?: boolean;
        };
        "models.DeleteRecordRequest": {
            /** @example mydevice.local */
            domain: string;
        };
        "models.QueryLog": {
            /** @example forwarded */
            action?: components["schemas"]["models.Action"];
            /** @example 93.184.216.34,93.184.216.35 */
            all_answers?: string;
            /** @example 2 */
            answer_count?: number;
            /** @example 192.168.1.5 */
            client_ip?: string;
            /** @example example.com */
            domain?: string;
            /** @example 1 */
            id?: number;
            /** @example 12.5 */
            latency_ms?: number;
            /** @example aa:bb:cc:dd:ee:ff */
            mac_address?: string;
            /** @example UDP */
            protocol?: string;
            /** @example A */
            query_type?: string;
            /** @example NOERROR */
            response_code?: string;
            /** @example 93.184.216.34 */
            resolved_ip?: string;
            /** @example 2024-10-25T10:00:00Z */
            timestamp?: string;
            /** @example 300 */
            ttl?: number;
            /** @example 1.1.1.1:53 */
            upstream_resolver?: string;
        };
        "models.RemoveBlockRequest": {
            /** @example ads.example.com */
            domain: string;
        };
        "models.Stats": {
            /** @example 45 */
            cache_hits?: number;
            /** @example 175 */
            cache_misses?: number;
            /** @example 100 */
            cache_size?: number;
            /** @example 20 */
            queries_blocked?: number;
            /** @example 45 */
            queries_cached?: number;
            /** @example 5 */
            queries_custom?: number;
            /** @example 150 */
            queries_forwarded?: number;
            /** @example 3600.5 */
            uptime_seconds?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
